# Welcome to Jekyll!

# Website settings
title: Ant贸nio Ferreira
description: Ant贸nio Ferreira's portfolio
keywords: Materials Science and Engineering, Georgia Tech
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://antonioferreira.life  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author: # change following line to your infomation.
  name: Ant贸nio Ferreira  # Be used at blog posts' author.
  first_name: Ant贸nio  # Be used at index page about me section.
  last_name: Ferreira  # Be used at index page about me section.
  avatar: /static/assets/img/headshot.jpg  # upload your avatar at directory and edit it.
  github_username:  # Leave blank if you don't have now
  linkedin_id: antonio-ferreira2003 # Leave blank if you don't have now
  facebook_username:  # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: aferreira32@gatech.edu  # Leave blank if you don't have now
  cv: http://antonioferreira.life/Antonio_Ferreira_Senior_MSE.pdf  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: 
    - name: 
  skill_icon2:
    - name: 
    - name: 
  desc: Born and raised in Portugal, I'm a Materials Science & Engineering student and Materials Thermodynamics (MSE 3001) teaching assistant at Georgia Tech. My interests in the field are broad and range from shape memory alloys and additive manufacturing technologies, to materials for energy applications and their processing. Outside school I enjoy travelling, practicing sports and hanging out with friends, and currently I'm following Dr. Spark's online course on Materials Informactics to develop programming skills in the field of MSE.  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name:

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

